$("#subplus1").click(function(){
    $(".head2").slideToggle('100')
});
$("#subplus2").click(function(){
  $(".head3").slideToggle('100')
});
$("#subplus3").click(function(){
  $(".head4").slideToggle('100')
});
$("#subplus4").click(function(){
  $(".head5").slideToggle('100')
});
$("#subplus5").click(function(){
  $(".head6").slideToggle('100')
});
$("#subplus6").click(function(){
  $(".head7").slideToggle('100')
});
$("#subplus7").click(function(){
  $(".head8").slideToggle('100')
});
$("#subplus1").click(function(){
  $(".head8").slideToggle('100')
});

$("#belowPlus").click(function(){
  $(".below2").slideToggle('200')
});